# Copyright 2022 san kim
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# docker build -t keti/image_retriever:v1 .
# docker tag keti/image_retriever:v1 10.0.0.161:5000/image_retriever:v1
# docker push 10.0.0.161:5000/image_retriever:v1

# docker run --gpus all --rm -it -p 5000:5000 -v $(pwd)/data:/root/app/data --name image_retriever keti/image_retriever:v1
# docker run --gpus all --rm -d -it -p 5000:5000 --name image_retriever keti/image_retriever:v1


FROM pytorch/pytorch:1.11.0-cuda11.3-cudnn8-devel
LABEL maintainer "KETI AIRC sankim <kimsan0622@keti.re.kr>"

ENV DEBIAN_FRONTEND noninteractive

ADD app/requirements.txt /root/app/
WORKDIR /root/app
RUN pip install -r requirements.txt
ADD app/*.py /root/app/

CMD ["python", "-m", "flask", "run", "--host=0.0.0.0"]

ENV SERVICE_PORT 5000
EXPOSE ${SERVICE_PORT}